/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AjsCounter {
        "initValue": number;
    }
}
declare global {
    interface HTMLAjsCounterElement extends Components.AjsCounter, HTMLStencilElement {
    }
    var HTMLAjsCounterElement: {
        prototype: HTMLAjsCounterElement;
        new (): HTMLAjsCounterElement;
    };
    interface HTMLElementTagNameMap {
        "ajs-counter": HTMLAjsCounterElement;
    }
}
declare namespace LocalJSX {
    interface AjsCounter {
        "initValue"?: number;
        "onCounterValueChange"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "ajs-counter": AjsCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ajs-counter": LocalJSX.AjsCounter & JSXBase.HTMLAttributes<HTMLAjsCounterElement>;
        }
    }
}
